language: python
python: '3.6'
install:
- pip install .
- pip install coveralls
- pip install --upgrade build
- pip install --upgrade twine
- pip install sphinx
- pip install sphinx_rtd_theme
script:
- coverage run -m unittest discover
after_success: coveralls
