language: python
python: '3.6'
install:
- pip install .
- pip install coveralls
- pip install --upgrade build
- pip install --upgrade twine
script:
- coverage run -m unittest discover
after_success: coveralls
