name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Sphinx Build
      # You may pin to the exact commit or the version.
      # uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "/docs/source"
        build-command: "sphinx-build source build"
     
    - name: artifact
      uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
