# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pypi-publish
    # You may pin to the exact commit or the version.
    # uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    uses: pypa/gh-action-pypi-publish@v1.4.2
    with:
      # PyPI user
      #user: # optional, default is __token__
      # Password for your PyPI user or an access token
      password: secrets.PYPI_TOCKEN
      # The repository URL to use
      repository_url: https://pypi.org/project/casing/
      # The target directory for distribution
      #packages_dir: # optional, default is dist
      # Check metadata before uploading
      #verify_metadata: # optional, default is true
      # Do not fail if a Python package distribution exists in the target package index
      #skip_existing: # optional
      # Show verbose output.
      #verbose: # optional
    
    
    
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
